version: "3.7"

services:
  # Manages the files (upload, delete, modify) 
  data_management:
    build: 
      context: ./backend/data_management/
      target: debug #debug mode with nodemon running!
    volumes: 
      - ./backend/data_management/src/:/work/src/
      - ./files/:/work/files/
    ports:
      - 6000:6000

  # Manages the microservices (upload, use)
  service_management:
    build:
      context: ./backend/service_management/
      target: debug #debug mode with nodemon running!
    volumes:
      - ./backend/service_management/src/:/work/src/
      - ./files/:/work/files/
      - ./microservices/:/work/services/
    ports:
      - 6001:6001

  # Stores metadata of the exposed microservices
  service_db:
    image: mongo:latest
    restart: always
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017  

  # # vue frontend // platform
  # frontend:
  #   build:
  #     context: ./frontend/
  #     target: debug #debug mode with serve
  #   volumes:
  #     - ./frontend/src/:/work/src/
  #   ports: 
  #     - 8080:8080

  # kafka is built on zookeeper
  zookeeper:
    image: bitnami/zookeeper:3-debian-10
    ports:
      - 2181:2181
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:2-debian-10
    ports:
      - 9092:9092
    volumes:
      - kafka_data:/bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - 9100:9000
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
      - JVM_OPTS=-Xms32M -Xmx64M
    depends_on:
      - kafka

  # api gateway
  kong:
    image: kong:latest
    volumes:
      - ./kong.yaml:/kong.yaml
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong.yaml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - 8000:8000 
      - 8443:8443 
      - 127.0.0.1:8001:8001 
      - 127.0.0.1:8444:8444 

volumes:
  zookeeper_data:
  kafka_data: