version: "3.7"

services:
  data_management:
    build: 
      context: ./backend/data_management/
      target: debug #debug mode with nodemon running!
    volumes: 
      - ./backend/data_management/src/:/work/src/
      - ./files/:/work/files/
    ports:
      - 6000:6000

  service_management:
    build:
      context: ./backend/service_management/
      target: debug #debug mode with nodemon running!
    volumes:
      - ./backend/service_management/src/:/work/src/
      - ./files/:/work/files/
    ports:
      - 6001:6001

  service_db:
    image: mongo
    ports:
      - 27018:27017  

  # frontend:
  #   build:
  #     context: ./frontend/
  #     target: debug #debug mode with serve
  #   volumes:
  #     - ./frontend/src/:/work/src/
  #   ports: 
  #     - 8080:8080

  kong:
    image: kong:latest
    volumes:
      - ./kong.yaml:/kong.yaml
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong.yaml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - 8000:8000 
      - 8443:8443 
      - 127.0.0.1:8001:8001 
      - 127.0.0.1:8444:8444 